version: "3"
services:
  vehicle_simulator_gz_sim:
    image: gazebo-vehicle-ros2-gpu-harmonic:jazzy
    container_name: vehicle_simulator_gz_sim
    volumes:
      #full dev
      - /dev:/dev:rw
      #full media
      - /media:/media:rw
      #Time
      - /etc/timezone:/etc/timezone:rw
      - /etc/localtime:/etc/localtime:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #ros-workspaces
      - ./root_dir/.ros:/root/.ros:rw
      - ./root_dir/.bash_profile:/root/.bash_profile:rw
      - ./root_dir/.bashrc:/root/.bashrc:rw
      - ./root_dir/.rangerdir:/root/.rangerdir:rw
      - ./root_dir/.tmux.conf:/root/.tmux.conf:rw
      - ./root_dir/simulation.rviz:/root/simulation.rviz:rw
      #packages
      - ./ros_env_vars.sh:/root/ros_env_vars.sh:rw
      - ./launch_simulation.sh:/root/launch_simulation.sh:rw
      - ./ros2_ws:/root/ros2_ws:rw
      - ./other_ws:/root/other_ws:rw
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    ipc: host
    pid: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
      - TERM
      - QT_X11_NO_MITSHM=1
    entrypoint: /bin/bash
